version: '3.9'

services:
  client:
    container_name: client
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    depends_on:
      - server
    command: npm start
  server:
    container_name: server
    image: server
    build: ./server
    ports:
      - 5001:5000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db 
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}